name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.7.2
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: 
  grpc: 
  protobuf: 
  fixnum:
  googleapis_auth:
  gcloud: 
  asn1lib: 
  pointycastle: 

dev_dependencies:
  test:
  pedantic:
